"""Static MIME knowledge used by bounded file-content analysis."""

MIME_EXTENSIONS = {
    "application/gzip": ("gz",),
    "application/json": ("json",),
    "application/msword": ("doc",),
    "application/octet-stream": ("bin", "dat"),
    "application/pdf": ("pdf",),
    "application/rtf": ("rtf",),
    "application/vnd.ms-excel": ("xls",),
    "application/vnd.ms-powerpoint": ("ppt",),
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ("pptx",),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ("xlsx",),
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ("docx",),
    "application/vnd.sqlite3": ("sqlite", "sqlite3", "db"),
    "application/x-7z-compressed": ("7z",),
    "application/x-elf": ("elf",),
    "application/x-msdownload": ("exe", "dll"),
    "application/x-rar-compressed": ("rar",),
    "application/x-tar": ("tar",),
    "application/xml": ("xml",),
    "application/zip": ("zip",),
    "audio/flac": ("flac",),
    "audio/mpeg": ("mp3",),
    "audio/ogg": ("ogg", "oga"),
    "audio/wav": ("wav",),
    "font/otf": ("otf",),
    "font/ttf": ("ttf",),
    "font/woff": ("woff",),
    "font/woff2": ("woff2",),
    "image/bmp": ("bmp",),
    "image/gif": ("gif",),
    "image/jpeg": ("jpg", "jpeg"),
    "image/png": ("png",),
    "image/svg+xml": ("svg",),
    "image/tiff": ("tif", "tiff"),
    "image/webp": ("webp",),
    "text/css": ("css",),
    "text/csv": ("csv",),
    "text/html": ("html", "htm"),
    "text/javascript": ("js", "mjs", "cjs"),
    "text/markdown": ("md", "markdown"),
    "text/plain": ("txt", "text", "log", "ini", "conf"),
    "text/x-c": ("c", "h"),
    "text/x-c++": ("cpp", "cxx", "cc", "hpp"),
    "text/x-csharp": ("cs",),
    "text/x-java": ("java",),
    "text/x-perl": ("pl",),
    "text/x-php": ("php",),
    "text/x-python": ("py", "pyw"),
    "text/x-ruby": ("rb",),
    "text/x-shellscript": ("sh", "bash", "zsh"),
    "text/x-sql": ("sql",),
    "text/x-yaml": ("yaml", "yml"),
    "video/mp4": ("mp4",),
    "video/quicktime": ("mov",),
    "video/webm": ("webm",),
    "video/x-matroska": ("mkv",),
    "video/x-msvideo": ("avi",),
}

EXTENSION_MIME = {
    extension: mime_type
    for mime_type, extensions in MIME_EXTENSIONS.items()
    for extension in extensions
}

TEXTUAL_APPLICATION_MIMES = {
    "application/javascript",
    "application/json",
    "application/rtf",
    "application/xml",
    "application/x-httpd-php",
    "application/x-javascript",
    "application/x-yaml",
}

MIME_DESCRIPTIONS = {
    "application/gzip": "gzip-compressed data",
    "application/json": "JSON text",
    "application/octet-stream": "unidentified binary data",
    "application/pdf": "PDF document",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "Office Open XML presentation",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "Office Open XML spreadsheet",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "Office Open XML document",
    "application/vnd.sqlite3": "SQLite database",
    "application/x-7z-compressed": "7-Zip archive",
    "application/x-elf": "ELF executable or object",
    "application/x-msdownload": "Windows portable executable",
    "application/x-rar-compressed": "RAR archive",
    "application/zip": "ZIP archive",
    "audio/flac": "FLAC audio",
    "audio/mpeg": "MPEG audio",
    "audio/ogg": "Ogg audio",
    "audio/wav": "WAVE audio",
    "image/bmp": "BMP image",
    "image/gif": "GIF image",
    "image/jpeg": "JPEG image",
    "image/png": "PNG image",
    "image/tiff": "TIFF image",
    "image/webp": "WebP image",
    "text/html": "HTML text",
    "text/plain": "plain text",
    "video/mp4": "MP4 video",
    "video/webm": "WebM video",
    "video/x-msvideo": "AVI video",
}
