"""Onboarding for generated Node.js projects; no installation side effects."""

_CREDIT = """
## About the generator

Created with [QZX — Quick Zap Exchange](https://qzx.yumbale.com/en/),
created and maintained by **Alejandro Sánchez**.

This credits the generator, not the author of your application. You may edit
or remove this section; the generated project has no dependency on QZX.

[Support QZX](https://qzx.yumbale.com/en/donate) or
[discuss professional automation services](https://qzx.yumbale.com/en/professional-services).
A donation does not purchase support or a delivery commitment.
"""


def _running_steps(typescript: bool) -> str:
    if typescript:
        return """
## First run

Use an actively supported Node.js installation with npm. From this directory,
install the development tools and compile the application:

```sh
npm install
npm run build
npm start
```

The dependency installation can use the network; QZX did not run it for you.
For development without a separate build step, use `npm run dev` after installation.
"""
    return """
## First run — no dependency installation required

Use an actively supported Node.js installation. From this directory, run:

```sh
node index.js
```

`npm start` runs the same application. Neither command requires `npm install`
for this starter: its runtime uses no third-party packages.
"""


def _testing_steps(with_tests: bool, typescript: bool) -> str:
    if not with_tests:
        return """
## Tests

Test scaffolding was not requested. `npm test` deliberately exits nonzero
instead of presenting an untested application as a passing suite.
"""
    installation = "" if typescript else "npm install\n"
    return f"""
## Run the generated tests

Install the development tools before testing. Installation can use the network.

```sh
{installation}npm test -- --runInBand
```

Commit the generated `package-lock.json` with your project. Later, `npm ci`
reproduces those locked dependencies. Review dependencies before distribution.
"""


def node_project_readme(name: str, with_tests: bool, typescript: bool) -> str:
    """Describe exactly how the selected starter can be run and reused."""
    language = "TypeScript" if typescript else "JavaScript"
    module = "./dist/index.js" if typescript else "./index.js"
    return (
        f"# {name}\n\nA {language} starter generated by QZX.\n"
        + _running_steps(typescript)
        + f"""
Expected greeting:

```text
Hello, world from {name}!
```

## Reuse the functions

{"Build first, then import the compiled module." if typescript else "Import the module directly."}
Importing it does not print a greeting or run the application:

```js
const {{ hello, add }} = require('{module}');
console.log(JSON.stringify({{ greeting: hello(), sum: add(2, 3) }}));
```

The caller controls stdout, so its JSON can be used by other tools.
"""
        + _testing_steps(with_tests, typescript)
        + _CREDIT
    )
